### ISSUE TITLE
Checkboxes and Radio Button Labels using p tag instead of label

### ISSUE THREAD

**Issue by shartte** [PredixDev/px-forms-design#10]
Hi, 

in the demo for checkboxes and radio buttons, p-tags are being used instead of actual labels.
This makes it impossible to click the labels instead of the actual checkbox and it doesn't really associate the label with the input control as far as the browser is concerned.

When label tags are used instead, they get the wrong styling (smaller font, etc.) of normal labels because label--inline doesn't really reset that styling.

**Comment by mdwragg** [comment]
Hi,
It sounds like you're on it, can you send us a pull request with your proposed fix please?

Thanks.
