### ISSUE TITLE
Need <select> element documenting/in demo

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-forms-design#4]
I went searching for the select element in the demo and via the nav sidebar of the Predix-UI site and couldn't find the `<select>` element anywhere. We should probably add that.

**Comment by randyaskin** [comment]
I've added several keywords (input, select, multiselect, textarea, etc) to the search functionality on the Predix-UI site. Do we really want to highlight the select element in forms-design, or should we encourage them to use px-dropdown instead?

**Comment by randyaskin** [comment]
Added to demo in v0.3.28.

**Comment by mdwragg** [comment]
👍
