### ISSUE TITLE
The px-forms-design select classification does not match the px dropdown spec

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-forms-design#5]
The px-forms-designs select classification is inconsistent with the px-dropdown spec. Having two different styles is also confusing and creates inconsistencies across applications.

Current px-forms-designs select item:
![screen shot 2016-12-16 at 8 10 26 am](https://cloud.githubusercontent.com/assets/6137443/21273532/d7cb75ae-c378-11e6-8a69-530bc69be8cd.png)

![screen shot 2016-12-16 at 8 10 32 am](https://cloud.githubusercontent.com/assets/6137443/21273537/db249f5a-c378-11e6-8793-38316d8fbc9e.png)

Current px-dropdown: 
![screen shot 2016-12-16 at 10 21 54 am](https://cloud.githubusercontent.com/assets/6137443/21273682/84707016-c379-11e6-9184-5f72b482bd40.png)

Spec:
![screen shot 2016-12-16 at 10 20 15 am](https://cloud.githubusercontent.com/assets/6137443/21273621/49c4d0d8-c379-11e6-9b10-20df5825c250.png)

**Comment by mdwragg** [comment]
We love pull requests @arcpato!

**Comment by mdwragg** [comment]
Especially from somebody with your skills.... :-)

**Comment by arcpato** [comment]
I think this might need more discussion though. I've read a lot of articles where changing the option tags is not advisable, but we do have a dropdown component. So to me this is an inconsistency issue.

The only way I have seen of changing the option tag styles it is through javascript (like this fiddle I found http://jsfiddle.net/BB3JK/47/ ) that basically wraps the option and select tags into html with the specific style classes. But it might be an overkill.

**Comment by randyaskin** [comment]
I consider the px-dropdown to be a more advanced version of the select element provided in px-forms design. It's a polymer component and has checkbox-mode and eventually may have other options (disabled options, search / autocomplete, etc have all been requested) which set it apart from the simple select. The fact that the invoking element looks the same is enough, in my opinion.

**Comment by arcpato** [comment]
Hmm, I think that makes sense.  
I'll close this for now.
