### ISSUE TITLE
Select box not the same height as px-button

### ISSUE THREAD

**Issue by bdbonnet** [PredixDev/px-forms-design#6]
This is admittedly nit-picky, but the select box is 2 pixels shorter than the px-button due to
``height: calc(2em - 2px);``

![screen shot 2017-01-19 at 1 28 42 pm](https://cloud.githubusercontent.com/assets/8203907/22121864/3938d768-de4b-11e6-9212-ce663ab4e9b7.png)

It makes since this is the value for ``line-height`` since the border is not included in it's calculation, but since the select is already a border-box there's no need to subtract two from the height for the border.

**Comment by randyaskin** [comment]
Fixed in v1.1.4, good catch.
