### ISSUE TITLE
Placeholder text is not themed

### ISSUE THREAD

**Issue by Menkhaus-ge** [PredixDev/px-forms-design#7]
In dark theme since the hint text is not colored the text appears to be active. 

Text box with type: 
Active:
![screen shot 2017-03-01 at 11 11 06 am](https://cloud.githubusercontent.com/assets/14931112/23476535/ed421078-fe6f-11e6-9f53-217d488f4068.png)
Disabled: 
![screen shot 2017-03-01 at 11 11 18 am](https://cloud.githubusercontent.com/assets/14931112/23476538/ef4d6606-fe6f-11e6-83a1-788c7efe75e4.png)

Text box with hint text:
Active:
![screen shot 2017-03-01 at 11 06 06 am](https://cloud.githubusercontent.com/assets/14931112/23476567/0a3f85f2-fe70-11e6-9957-2f8a7f1cafdc.png)
Disabled:
![screen shot 2017-03-01 at 11 06 14 am](https://cloud.githubusercontent.com/assets/14931112/23476572/0c8bf570-fe70-11e6-9862-6ddfdd54440d.png)

**Comment by randyaskin** [comment]
Fixed in v1.2.3
