### ISSUE TITLE
input types 'email' and 'password' are not showing expected icons 

### ISSUE THREAD

**Issue by Menkhaus-ge** [PredixDev/px-forms-design#9]
When type="email" the input field should show an icon on the right. 
Expected:
![screen shot 2017-03-02 at 3 53 59 pm](https://cloud.githubusercontent.com/assets/14931112/23533649/eb5990c6-ff67-11e6-85d9-4bda432df533.png)

**Comment by randyaskin** [comment]
I believe that's your browser's autofill functionality kicking in - there's nothing in the code to indicate that an icon should be displayed.
